import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MyNav from "@/components/MyNav";
import Footer from '@/components/Footer'; 
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <MyNav />
          <Suspense>
            {children}
          </Suspense>
        <Footer />
      </body>
    </html>
  );
}



// import './globals.css'
// import { Inter } from 'next/font/google'
// import MyNav from '@/components/MyNav';
// import Footer from '@/components/Footer';

// const inter = Inter({ subsets: ['latin'] })
//  export const metadata = {
//  title: 'Create Next App',
//  description: 'Generated by create next app',
//  }
// export default function RootLayout({
//  children,
// }: {
//  children: React.ReactNode
// }) {
//  return (
//  <html lang="en">
//  <body className={inter.className}>
//  <MyNav />
//  {children}
//  <Footer />
//  </body>
//  </html>
//  )
//  } 